# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Configuru < Formula
  desc ""
  homepage ""
  version "0.0.1-rc3"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/42nerds/configuru/releases/download/0.0.1-rc3/configuru_0.0.1-rc3_Darwin_x86_64.tar.gz"
    sha256 "dfcef451259fd578133f93da1eac9a07c8a8b60ccb67e248ba0326568df4fbe5"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/42nerds/configuru/releases/download/0.0.1-rc3/configuru_0.0.1-rc3_Darwin_arm64.tar.gz"
    sha256 "7986c61c1d3b8d4c48b80474f4675ef58e8209fee2762d63a7174c8d72b856b0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/42nerds/configuru/releases/download/0.0.1-rc3/configuru_0.0.1-rc3_Linux_x86_64.tar.gz"
    sha256 "a709cd43ea27a73e760692e1e0ce4b715b316acc637301c984c0ab2a6ec83e08"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/42nerds/configuru/releases/download/0.0.1-rc3/configuru_0.0.1-rc3_Linux_arm64.tar.gz"
    sha256 "6620fc92027c0dda1564777868a1fe793a5b2dd9dca042f6006799dda6ddb573"
  end

  head "https://github.com/42nerds/configurur.git?ref=develop"

  def install
    bin.install "configuru"
  end
end
