# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Configuru < Formula
  desc ""
  homepage ""
  version "0.0.1-rc4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/42nerds/configuru/releases/download/0.0.1-rc4/configuru_0.0.1-rc4_Darwin_x86_64.tar.gz"
    sha256 "32bbfbd1579bdc7b2bc6a9cad74e4e5e9ddd23c7f6e8c369b010c4ed85d21e2e"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/42nerds/configuru/releases/download/0.0.1-rc4/configuru_0.0.1-rc4_Darwin_arm64.tar.gz"
    sha256 "375260c2325b9348e4f432dfbefc2f090b7f8f34b82ea143206ce47982e63b69"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/42nerds/configuru/releases/download/0.0.1-rc4/configuru_0.0.1-rc4_Linux_x86_64.tar.gz"
    sha256 "b06cbf62b1b1146de68b197570cc1256ae40ff111d313235097395d9d660ef72"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/42nerds/configuru/releases/download/0.0.1-rc4/configuru_0.0.1-rc4_Linux_arm64.tar.gz"
    sha256 "4672e2d5ab7607bd2e0c3fa08e518ee9e2cc693710c08ca2ca29771cf75ad1c4"
  end

  head "https://github.com/42nerds/configuru.git?ref=develop"

  def install
    bin.install "configuru"
  end
end
